// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeqMBPOHHD6vG2i_r7KYZ-bYllR5M6Yns',
    appId: '1:301491189774:web:a3e82a0a1cfac2086b245f',
    messagingSenderId: '301491189774',
    projectId: 'valwaste-89930',
    authDomain: 'valwaste-89930.firebaseapp.com',
    storageBucket: 'valwaste-89930.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeqMBPOHHD6vG2i_r7KYZ-bYllR5M6Yns',
    appId: '1:301491189774:android:a3e82a0a1cfac2086b245f',
    messagingSenderId: '301491189774',
    projectId: 'valwaste-89930',
    storageBucket: 'valwaste-89930.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeqMBPOHHD6vG2i_r7KYZ-bYllR5M6Yns',
    appId: '1:301491189774:ios:a3e82a0a1cfac2086b245f',
    messagingSenderId: '301491189774',
    projectId: 'valwaste-89930',
    storageBucket: 'valwaste-89930.firebasestorage.app',
    iosClientId: '301491189774-abcdefghijklmnop.apps.googleusercontent.com',
    iosBundleId: 'com.valwaste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeqMBPOHHD6vG2i_r7KYZ-bYllR5M6Yns',
    appId: '1:301491189774:ios:a3e82a0a1cfac2086b245f',
    messagingSenderId: '301491189774',
    projectId: 'valwaste-89930',
    storageBucket: 'valwaste-89930.firebasestorage.app',
    iosClientId: '301491189774-abcdefghijklmnop.apps.googleusercontent.com',
    iosBundleId: 'com.valwaste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeqMBPOHHD6vG2i_r7KYZ-bYllR5M6Yns',
    appId: '1:301491189774:web:a3e82a0a1cfac2086b245f',
    messagingSenderId: '301491189774',
    projectId: 'valwaste-89930',
    storageBucket: 'valwaste-89930.firebasestorage.app',
  );
}
